ShaneBeee/SkBee

src/main/java/com/shanebeestudios/skbee/elements/text/expressions/ExprHoverEvent.java

Minecraft likes just LF, but System#lineSeperator can return CRLF on some platforms like Windows. This causes an erroneous "CR" character to be displayed in the hover text.

Fix line seperator in hover event expression

---

src/main/java/com/shanebeestudios/skbee/elements/recipe/expressions/ExprIngredientsOfRecipe.java

Fixes the issue described in #298.
Seems like the problem was that shaped recipes that are 3 slots wide but less than 3 slots tall didn't get a big enough ArrayList to store their items.
Some example items are `minecraft:oak_boat` and `minecraft:oak_slab`.
```
[18:47:16 INFO]: executing 'send ingredients of recipe "minecraft:oak_boat"'
[18:47:16 INFO]: oak wood planks
[18:47:16 INFO]: air
[18:47:16 INFO]: oak wood planks
[18:47:16 INFO]: oak wood planks
[18:47:16 INFO]: oak wood planks
[18:47:16 INFO]: oak wood planks
[18:47:16 INFO]: air
[18:47:16 INFO]: air
[18:47:16 INFO]: air
[18:47:18 INFO]: executing 'send ingredients of recipe "minecraft:oak_slab"'
[18:47:18 INFO]: oak wood planks
[18:47:18 INFO]: oak wood planks
[18:47:18 INFO]: oak wood planks
[18:47:18 INFO]: air
[18:47:18 …
```

ExprIngredientsOfRecipe - fix shaped recipes that are 3 slots wide but not 3 slots tall

---

src/main/java/com/shanebeestudios/skbee/api/text/BeeComponent.java
src/main/java/com/shanebeestudios/skbee/elements/text/effects/EffSendComponent.java
src/main/java/com/shanebeestudios/skbee/elements/text/expressions/ExprMergeComponents.java

Congrates, probably the smallest pr I have planned <3 
This pr aims to add an optional delimiter to the merge components expression while also adding a '-' to the send component effect for command sender
Send component didn't return any known errors but one of my failed builds sent an error at that point which made me aware of this issue.

ExprMergeComponents | Add delimiter

---

src/main/java/com/shanebeestudios/skbee/api/nbt/NBTApi.java
src/main/java/com/shanebeestudios/skbee/api/nbt/NBTCustomType.java
src/main/java/com/shanebeestudios/skbee/elements/nbt/effects/EffSpawnEntityNBT.java
src/main/java/com/shanebeestudios/skbee/elements/nbt/expressions/ExprItemWithNBT.java
src/main/java/com/shanebeestudios/skbee/elements/nbt/expressions/ExprTagOfNBT.java

This PR aims to add the ability to add/remove to/from nbt tags.
Making `%nbttype%` now a literal, error messages will be better and easier to understand.
This should not create an breaking changes.

ExprTagOfNBT - add option to add/remove to/from tags

---

src/main/java/com/shanebeestudios/skbee/api/listener/NBTListener.java
src/main/java/com/shanebeestudios/skbee/api/recipe/RecipeUtil.java
src/main/java/com/shanebeestudios/skbee/api/util/Util.java
src/main/java/com/shanebeestudios/skbee/config/Config.java
src/main/java/com/shanebeestudios/skbee/elements/gameevent/type/Types.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprNamespacedKey.java
src/main/resources/config.yml

- `NBT EVENTS` has been moved out of `elements.nbt-events.`
- `NBT EVENTS` now has it's own config section and is no longer polluting `elements` 
- `RECIPE` has been removed and `recipe.namespace` was moved to `settings.namespace`
- `RecipeUtils#getKey` has been marked as deprecated, and will be removed in a future release
- `ExprNamespacedKey` has been changed from `Util#getMCNamespacedKey` to just `#getNamespacedKey`, it no longer defaults to `minecraft:`
- Added optional minecraft parse tag for using minecraft namespace in ExprNamespacedKey
- `Types.GameEvent` classinfo has been changed to error depending on config debug state
<details>
<summary><bold>CLICK THIS TO SHOW REASONS</bold></summary>
SNBT events didn't make sense to stay within `elements`, they're closely tied with NBT so as …

⭐ Config and Namespace changes

---

src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprSuspiciousBlock.java

This expression no longer worked when using 1.20 anymore it seemed, a user on discord pointed out to me that it was returning none even with items. After a quick look around turns out there was a new Brushable class for these blocks added which now includes gravel and sand. 
Changes made
- Made expression only work if the Brushable class exists
- Add isAir check to item and return null if it's air (I don't know if it original returned air but it does now)
- Updated interals to use Brushable class which adds support for suspicious gravel 
If you have any idea on how to update the documentation annotations that'll be great as now it's only 1.20 not 1.19.4

ExprSuspiciousBlock - Fix a 1.20 issue

---

src/main/java/com/shanebeestudios/skbee/elements/other/conditions/CondSpawnerIsActivated.java
src/main/java/com/shanebeestudios/skbee/elements/other/effects/EffSpawnerResetTimer.java
src/main/java/com/shanebeestudios/skbee/elements/other/events/EvtSpawnerSpawn.java
src/main/java/com/shanebeestudios/skbee/elements/other/events/OtherEvents.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprSpawnerMaxNearbyEntities.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprSpawnerRequiredPlayerRange.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprSpawnerSpawnCount.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprSpawnerSpawnDelay.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprSpawnerSpawnRange.java

This PR adds a bunch of spawner related syntax
A list of everything added is below
- Added CondSpawnerIsActivated
- Added EffSpawnerResetTimer (PaperMC)
- Added EvtSpawnerSpawn
- Added ExprSpawnerRequiredPlayerRange
- Added ExprSpawnerSpawnCount
- Added ExprSpawnerSpawnDelay
- Added ExprSpawnerSpawnRange
- Added ExprSpawnerMaxNearbyEntities
officially I spent far too many days working on this and now I must go to sleep as I work in about 10 hours
majority of the descriptions are copied from the javadocs.
I added a comment on `ExprSpawnerRequiredPlayerRange` as it states `<= 0` for infinite range which is false it's only `< 0`
if the range is set to 0 it's disabled even disables the spawn delay

Add spawner support

---

src/main/java/com/shanebeestudios/skbee/elements/other/conditions/CondIsLocked.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprLockableKey.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprLockableLock.java

Adds support for the lockable block state includes everything container and beacons
the lockable state is a interface instead of a stand alone class to extend stupidly so must check for container and beacon classes
as such

Add Lockable block state

---

src/main/java/com/shanebeestudios/skbee/elements/other/effects/EffAbortSpawn.java
src/main/java/com/shanebeestudios/skbee/elements/other/events/EvtPreSpawn.java

Stupid system forcing a creation
This PRs adds paper's three events for pre spawning 
- PreCreatureSpawnEvent (called before bukkit's creature spawn event)
- PreSpawnerSpawnEvent (called before bukkit's spawner spawn event)
- PhantomPreSpawnEvent (unsure much use for it but as it existed added it)
In addition added an effect for aborting the spawn events, if used the entity will not attempt to respawn again.
Didn't want to add this with the spawner support PR so waited until that was merged

Add paper's pre spawn events

---

src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprQuitReason.java

Fixed an issue with servers running spigot and skbee registering the ExprQuitReason when they can't even use it

ExprQuitReason - Fix Spigot server errors

---

src/main/java/com/shanebeestudios/skbee/elements/text/sections/SecClickEventCallback.java

- Swapped section from `EffectSection` to `Section` and cleaned it up a bit
- Updated some examples to showcase the usage of `lifetime` and `uses`
- Added `duration` into the `lifetime` portion allowing more possible combinations
The swap from `EffectSection` to `Section` was by tud pointing out on discord it didn't make much sense to use it if we can't allow one line usage anyways, the only reason I found why you'd do this is adding a custom error message, however I don't believe this a good practice to follow and believe it's best to stop before it's started.
Some cleanup to the class was made with the removal of nullable properties allowing a little bit easier readability. renamed the `timeLimit` field to `lifeTime` making it a bit more intuitive, and lastly made the event private as …

SecClickEventCallback - Some minor cleanup changes

---

src/main/java/com/shanebeestudios/skbee/elements/fishing/expressions/ExprFishHookWaitTime.java

This pr aims to fix an issue with how we handled fishing min/max wait time. When attempting to set maximum/minimum wait time in certain orders with a higher/lower value than default would cause one or the other to not update to new values. Refer to screenshots for showcase.
Solution was to remove clamping between min/max values and set min/max if value is lower/greater than
Top half I set min then set max
Bottom half I set max then I set min
- Related Issue: #605

Bug - Fishing Min/Max 

---

src/main/java/com/shanebeestudios/skbee/elements/villager/expressions/ExprMerchantRecipes.java

Omg, where do I even start with this class. For starters this pr aims to fix the issue mentioned in #616. Somewhere within the 3 places `delta` was used there was cases where delta wasn't set, this seems most likely to stem from `delete` changer not existing but #616 proves it existed under the set changer as well.
Honestly I'm not 100% sure what the issue was but with how that class was actually set up it wouldn't shock me if a bitcoin miner existed inside it. however after messing around and cleaning it up it seems like the issue was solved and more proper checks were created. The systems internally were heavily a mess and melded together as such they've been split this allowed introduction of the `delete` change into `merchant recipe x of y` expression.
This pr adds 2 *minor* …

ExprMerchantRecipes - cleanup and fix

---

src/main/java/com/shanebeestudios/skbee/api/wrapper/RegistryWrapper.java
src/main/java/com/shanebeestudios/skbee/elements/generator/effects/EffChunkDataStructurePlace.java
src/main/java/com/shanebeestudios/skbee/elements/generator/effects/EffPopulateTree.java
src/main/java/com/shanebeestudios/skbee/elements/generator/effects/EffTreeGenerate.java
src/main/java/com/shanebeestudios/skbee/elements/generator/expressions/ExprChunkDataBiome.java
src/main/java/com/shanebeestudios/skbee/elements/generator/expressions/ExprChunkDataBlock.java
src/main/java/com/shanebeestudios/skbee/elements/generator/expressions/ExprChunkDataHighestY.java
src/main/java/com/shanebeestudios/skbee/elements/nbt/expressions/ExprTagOfNBT.java
src/main/java/com/shanebeestudios/skbee/elements/other/effects/EffTransferCookieRetrieve.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprTransferCookie.java
src/main/java/com/shanebeestudios/skbee/elements/other/sections/SecTransferCookieRetrieve.java
src/main/java/com/shanebeestudios/skbee/elements/other/type/Types.java
src/main/java/com/shanebeestudios/skbee/elements/team/expressions/ExprTeamColor.java
src/main/java/com/shanebeestudios/skbee/elements/text/expressions/ExprAsyncChatViewers.java
src/main/java/com/shanebeestudios/skbee/elements/worldcreator/expressions/ExprLoadedCustomWorlds.java
src/main/java/com/shanebeestudios/skbee/elements/worldcreator/objects/BeeWorldConfig.java

Preparation for future patch release.
Temp changelog:
- Fixed a long standing casting issue when using the NBT tag expression nested within other expressions
- Fixed an error when attempting to get key of an invalid registry wrapper object (this can happen with reflect)
- Fixed an issue with the chunkdata biome expression not being properly shifted
- Added a section for retrieving cookies
- Added an expression to get the cookie in a cookie retrieval section
- Added an expression for chat viewers in the async chat event
- Added an expression to get all loaded custom worlds
- Added an effect/type to populate trees in a chunk generator
- Added an expression to get the highest block Y in a chunk generator block pop section
- Deprecated cookie retrieval effect (using section instead)
- …

Dev/Patch - Future Release

---

build.gradle
src/main/java/com/shanebeestudios/skbee/api/generator/ChunkGenerator.java
src/main/java/com/shanebeestudios/skbee/api/generator/event/BlockPopulateEvent.java
src/main/java/com/shanebeestudios/skbee/api/nbt/NBTApi.java
src/main/java/com/shanebeestudios/skbee/api/nbt/NBTCustomEntity.java
src/main/java/com/shanebeestudios/skbee/api/nbt/NBTCustomItemStack.java
src/main/java/com/shanebeestudios/skbee/api/nbt/NBTCustomTileEntity.java
src/main/java/com/shanebeestudios/skbee/api/nbt/NBTCustomType.java
src/main/java/com/shanebeestudios/skbee/api/util/ObjectConverter.java
src/main/java/com/shanebeestudios/skbee/api/util/Util.java
src/main/java/com/shanebeestudios/skbee/elements/generator/effects/EffPopulateTree.java
src/main/java/com/shanebeestudios/skbee/elements/generator/expressions/ExprChunkDataBlock.java
src/main/java/com/shanebeestudios/skbee/elements/nbt/expressions/ExprItemFromNBT.java
src/main/java/com/shanebeestudios/skbee/elements/nbt/expressions/ExprNbtCompound.java
src/main/java/com/shanebeestudios/skbee/elements/nbt/types/SkriptTypes.java
src/main/java/com/shanebeestudios/skbee/elements/other/effects/EffEquipmentChange.java
src/main/java/com/shanebeestudios/skbee/elements/other/effects/EffLootTableFillInv.java
src/main/java/com/shanebeestudios/skbee/elements/other/events/PaperEvents.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprAvailableMaterials.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprAverageTickTime.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprEntityPose.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprLootTableItems.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprNearestEntity.java
src/main/java/com/shanebeestudios/skbee/elements/other/type/Types.java
src/main/java/com/shanebeestudios/skbee/elements/worldcreator/expressions/ExprWorldCreator.java
src/main/java/com/shanebeestudios/skbee/elements/worldcreator/objects/BeeWorldConfig.java
src/main/java/com/shanebeestudios/skbee/elements/worldcreator/objects/BeeWorldCreator.java
src/main/resources/lang/english.lang

Temp Changelog:
- Added an expression to get average tick time 
- Added a type and expression for entity pose
- Added an option to add a namespaced key to world creators
- Added support for multiple slots in the equipment slot effect
- Added support for Minecraft 1.21 NBT
- Appended the suffix "face" to the BlockFace type to fix comparison/clashing issues with Direction
- Added `excluding %entities%` to nearest entity expression
- Added slime pathfinding to pathfinding event (for some reason paper made this separate)
- Changed how Random is handled in the populate tree effect (helps for better consistency)
- Internal change with file nbt, clear compound before deleting file (this shouldn't affect anyone)
- Removed clamping in chunkdata block expression (allowing to reach into neighbouring …

Dev/Patch - Prepare for future release

---

build.gradle
src/main/java/com/shanebeestudios/skbee/AddonLoader.java
src/main/java/com/shanebeestudios/skbee/api/bound/Bound.java
src/main/java/com/shanebeestudios/skbee/api/nbt/NBTApi.java
src/main/java/com/shanebeestudios/skbee/api/nbt/NBTCustomItemStack.java
src/main/java/com/shanebeestudios/skbee/api/wrapper/ComponentWrapper.java
src/main/java/com/shanebeestudios/skbee/elements/other/effects/EffBreakBlocksWithEffects.java
src/main/java/com/shanebeestudios/skbee/elements/other/events/OtherEvents.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprChunksWithinCuboid.java
src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprLootTableObject.java
src/main/java/com/shanebeestudios/skbee/elements/other/sections/SecAttributeModifier.java
src/main/java/com/shanebeestudios/skbee/elements/other/type/Types.java
src/main/java/com/shanebeestudios/skbee/elements/recipe/events/EvtRecipe.java
src/main/java/com/shanebeestudios/skbee/elements/recipe/expressions/ExprRecipeResultSlot.java
src/main/java/com/shanebeestudios/skbee/elements/text/effects/EffComponentReplace.java
src/main/java/com/shanebeestudios/skbee/elements/villager/effects/EffVillagerEffects.java

- Fixed an error when attempting to wake up a villager that isn't sleeping
- Fixed an issue with modifying `full nbt of %item%` throwing Minecraft component errors to console
- Fixed an error when applying an attribute modifier to an entity which doesn't have that attribute.
- Fixed an issue where an empty list/array is left in an NBT compound after removing from it (and often returning an incorrect tag type)
- Fixed an error when running a Spigot server and another plugin has added AdventureAPI
- Fixed an error with component replace when a regex pattern is broken
- Fixed an issue when copying bounds, and the owner was copied into members
- Fixed an issue where the bound owners/members list was not cloned but referenced when copying a bound (therefor linking the two)
- Added crafter …

Dev/Patch - future update

---

src/main/java/com/shanebeestudios/skbee/api/recipe/RecipeUtil.java
src/main/java/com/shanebeestudios/skbee/api/util/Util.java
src/main/java/com/shanebeestudios/skbee/elements/other/type/Comps.java
src/main/java/com/shanebeestudios/skbee/elements/recipe/expressions/ExprMaterialChoice.java
src/main/java/com/shanebeestudios/skbee/elements/recipe/type/Types.java
src/main/java/com/shanebeestudios/skbee/elements/switchcase/effects/EffCase.java
src/main/java/com/shanebeestudios/skbee/elements/switchcase/expressions/ExprSwitchedObject.java
src/main/java/com/shanebeestudios/skbee/elements/switchcase/sections/SecCase.java
src/main/java/com/shanebeestudios/skbee/elements/switchcase/sections/SecExprSwitchReturn.java
src/main/java/com/shanebeestudios/skbee/elements/switchcase/sections/SecSwitch.java
src/test/scripts/general/switch-case.sk

This PR aims to fix/change some things with Switch Cases:
- Fix an issue where normal and inline cases cannot be used together in a switch section.
- Fix event-values not working in cases
- Added a check to prevent non-case code in switch sections.
- Temporarily add item/entitytype to tag comparators (until Skript adds them) so tags can be used in cases
---
**Target Minecraft Versions:** any   
**Requirements:** none   
**Related Issues:** #730, #733, https://github.com/SkriptLang/Skript/issues/7465

SwitchCase - fix normal/inline cases not working together

---

src/main/java/com/shanebeestudios/skbee/elements/recipe/expressions/ExprCraftingResultFromItems.java

This PR aims to fix an issue with using `getFirst`, not being supported on older java versions such as java 17 for 1.19.4
---
**Target Minecraft Versions:** any   
**Requirements:** none   
**Related Issues:** none

Fix NoMethodExists exception in ExprCraftingResultFromItems

---

src/main/java/com/shanebeestudios/skbee/api/wrapper/ComponentWrapper.java
src/main/java/com/shanebeestudios/skbee/elements/text/effects/EffComponentReplace.java
src/test/scripts/elements/text/effects/EffComponentReplace.sk

Yeah more, this time I've focused changes onto the EffComponentReplace class, as it's something I always use and have been annoyed with more times than I can count (not very high).
- The changes proposed here are to allow the ability to opt into regex replacement rather than forcing it.
- As well as the option to only replace the first of each matched keyword.
- Add support for using objects for replacement (minor but just a bit more flexible usage + lazy support)
Using `component replace first "X" and "Y" in {_var} with "Z"` will replace the first instance of both X and Y not one or the other this is due to patterns being reapplied each time.
Breaking change is caused by us now defaulting to literal match vs. regex match as players don't actively know regex, players who relied on this …

Component replace effect changes

---

src/main/java/com/shanebeestudios/skbee/elements/text/expressions/ExprEffectiveName.java

This PR aims to add support for the effective name of an ItemStack, this method is provided by paper as of 1.21.4.
Wasn't sure how viable a test would be for this, as the most we can test for currently is display name and item name not the potion display name or translation name.
---
**Target Minecraft Versions:** 1.21.4+   
**Requirements:** Paper   
**Related Issues:** none

Add effective name support

---

src/main/java/com/shanebeestudios/skbee/elements/raytrace/expressions/ExprRayTraceFromEntity.java
src/main/java/com/shanebeestudios/skbee/elements/raytrace/expressions/ExprRayTraceFromLocation.java

maxDistance is changed from int to a double because values like 0.25 or 0.1 turns into whole numbers like 0
---
**Target Minecraft Versions:** any   
**Requirements:** none   
**Related Issues:** none

maxDistance is changed from int to double
